django/crawler/urls.py
from django.urls import path

from . import views
from django.views import static
from django.conf import settings
from django.conf.urls import url

app_name = 'crawler'  # 设置命名空间
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('movies', views.show_movies, name='show_movies'),
    path('search', views.MoviesSearchView.as_view(), name='search'),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
]

django/maoyan_top100/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crawler.urls')),
    path('favicon.ico', RedirectView.as_view(url='../static/crawler/images/favicon.ico')),
]

django/crawler/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Top100(models.Model):
    ranking = models.IntegerField()
    title = models.CharField(unique=True, max_length=255)
    stars = models.CharField(max_length=255)
    release_time = models.CharField(max_length=255)
    score = models.FloatField()
    img_url = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        app_label = 'crawler'
        db_table = 'top_100'

django/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class Top100(models.Model):
    ranking = models.IntegerField()
    title = models.CharField(unique=True, max_length=255)
    stars = models.CharField(max_length=255)
    release_time = models.CharField(max_length=255)
    score = models.FloatField()
    img_url = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'top_100'

django/crawler/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.db import connections
from django.template import loader
from django.http import HttpResponse
from django.forms.models import model_to_dict
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage
from django.views.decorators import csrf
from crawler.models import *
import pprint


class IndexView(ListView):
    model = Top100
    template_name = 'crawler/index.html'
    context_object_name = 'index'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["table_title"] = "猫眼评分Top100"
        context["movies"] = Top100.objects.order_by("-score")
        return context


class MoviesSearchView(ListView):
    model = Top100
    template_name = 'crawler/index.html'
    context_object_name = 'search'

    def get_context_data(self, **kwargs):
        context = super(MoviesSearchView, self).get_context_data(**kwargs)
        context["movies"] = Top100.objects.all()[:10]
        if self.request.GET:
            search_type = self.request.GET['s']
            search_key = self.request.GET['q']
            context["table_title"] = f"{search_key} 查询结果"
            try:
                context["movies"] = []
                if search_type == "title":
                    context["movies"] = Top100.objects.filter(title__contains=search_key).order_by("-score")
                elif search_type == "stars":
                    context["movies"] = Top100.objects.filter(stars__contains=search_key).order_by("-score")
                elif search_type == "score_gt":
                    context["movies"] = Top100.objects.filter(score__gt=float(search_key)).order_by("-score")
                    context["table_title"] = f"评分大于 {float(search_key)} 查询结果"
                elif search_type == "score_lt":
                    context["movies"] = Top100.objects.filter(score__lt=float(search_key)).order_by("-score")
                    context["table_title"] = f"评分小于 {float(search_key)} 查询结果"
                elif search_type == "time_before":
                    context["movies"] = Top100.objects.filter(release_time__lt=search_key).order_by("-release_time")
                    context["table_title"] = f"上映时间 {search_key} 之前的查询结果"
                elif search_type == "time_after":
                    context["movies"] = Top100.objects.filter(release_time__gt=search_key).order_by("-release_time")
                    context["table_title"] = f"上映时间 {search_key} 之后的查询结果"
                if not context["movies"]:
                    context["table_title"] = "本此查询无匹配项目"
            except:
                context["table_title"] = "本此查询条件有误"

        return context


def show_movies(request):
    table_title = "猫眼Top100"
    movies_query = Top100.objects.all()
    if movies_query:
        movies = [model_to_dict(i) for i in Top100.objects.all()]
        movies = [i for i in movies]
    return render(request, 'crawler/index.html',
                  {'table_title': table_title, 'movies': movies})

django/crawler/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=0">
    <title>猫眼Top100爬虫</title>

    {% load static %}
    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="shortcut icon" href="{% static "crawler/images/favicon.ico" %}">
    <link rel="stylesheet" type="text/css" href="{% static 'crawler/css/styles.css' %}">
    <!-- js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/4.1.0/echarts-en.common.min.js"></script>
    <script src="{% static "crawler/js/script.js" %}"></script>
</head>

<body>
<nav>
    <!-- REPLACE IMG VALUE WITH LOGO -->
    <div>
        <a href="#">
            <img class="logo"
                 src="{% static "crawler/images/logo.png" %}"/></a>
    </div>
    {# <li class="nameTag">Hufe09</li> #}

    <div class="fullmenu">
        <img class="exit" src="https://raw.githubusercontent.com/hufe09/GitNote-Images/master/Picee/logo.7ete93wobu.png"/>
        <ul>
            <li><a href="{% url "crawler:index" %}"><strong>HOME</strong></a>

                <div class="dropdown">
                    <ul>
                        <li><a href='#'>SUB HEADING 1</a></li>
                        <li><a href='#'>SUB HEADING 2</a></li>
                        <li><a href='#'>SUB HEADING 3</a></li>
                    </ul>
                </div>
            </li>


            {# <li><a href="{% url "crawler:show_movies" %}"><strong>MOVIES</strong></a></li> #}
            <li><a href="{% url "crawler:search" %}"><strong>SEARCH</strong></a></li>
        </ul>
    </div> <!-- end of fullmenu for mobile -->
    {#    <img class="menu-icon" src="http://citysmokehousesf.com/images/menu_icon.png"/>#}
</nav>
{% block main %}

{% endblock main %}

{% block paging %}
{% endblock paging %}
</body>

</html>

django/crawler/templates/crawler/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{% block main %}


<h1 class="table_title">{{ table_title }}</h1>
<form action="/search" method="get" style="height: 50px;">
    {% csrf_token %}
    <select name="s">
        <option value="title">电影名</option>
        <option value="stars">演员</option>
        <option value="score_lt">评分(小于)</option>
        <option value="score_gt">评分(大于)</option>
        <option value="time_before">时间(之前)</option>
        <option value="time_after">时间(之后)</option>
    </select>
    <input type="text" name="q" style="height: 30px;">
    <input type="submit" value="Search">
</form>
{{ error }}
<div id="tableBox">
    {#绘制表格#}
    <table id='customers'>
        {# 表头内容 #}
        <tr>
            <th>排名</th>
            <th>电影</th>
            <th>评分</th>
            <th>演员</th>
            <th>上映时间</th>
            <th>电影海报</th>
        </tr>

        {% block content %}
        {# 表格内容 #}
        {% if object_list %}
        {% for movie in movies %}
        {% if forloop.counter|divisibleby:2 %}
        <tr class="alt">
            {% else %}
        <tr>
            {% endif %}
            <td>{{ movie.ranking }}</td>
            <td>{{ movie.title }}</td>
            <td>{{ movie.score }}</td>
            <td>{{ movie.stars }}</td>
            <td>{{ movie.release_time }}</td>
            <td><img src="{{ movie.img_url }}" alt="poster" style="height: 120px; width: 90px;"></td>
        </tr>
        {% endfor %}
        {% endif %}
        {% endblock content %}
    </table>
</div>

{% endblock main %}


</body>
</html>